package example:component@0.1.0

/// An example backend interface.
interface backend {
    /// Interface function
    fetch: func(url: string) -> list<u8>
    
    /// A resource containing a constructor, static function and a method
    resource scalars {
        /// constructor
        constructor()
        /// The first function, named get-a
        get-a: static func() -> u32
        /// The first function, named get-b
        get-b: func() -> u32

    }

    /// Interface function
    scalar-arg: func(x: borrow<scalars>) -> u32
}

/// An example world for the component to target.
world example {
    export backend
}


